### ISSUE TITLE
Pi 4 Support

### ISSUE THREAD

**Issue by peternewman** [simonhyde/PiClock#5]
More a flag currently than anything else, the upstream library doesn't currently work on a Pi 4:
https://github.com/ajstarks/openvg/issues/69

**Comment by simonhyde** [comment]
Yeah, annoying! I wrote it based upon the recommended accelerated way to do vector graphics when the first Raspberry Pi was released, sadly that API didn't really get much industry traction As noted in https://www.raspberrypi.org/forums/viewtopic.php?t=245380 there is no intention to support OpenVG on the graphics chipset of the Pi 4. Someone does note a couple of shim libraries which will work on top of OpenGL, further down the thread. I did some experimentation with these, and I think I got it vaguely working. The only way I could get them to working was by installing an X server, so there's obviously a higher installation footprint.

**Comment by peternewman** [comment]
> I did some experimentation with these, and I think I got it vaguely working. The only way I could get them to working was by installing an X server, so there's obviously a higher installation footprint.

Ah yes, I'd got it roughly working cross-platform using some of those, but just had X on and hadn't really considered the original didn't have it.

Are you able to push up your vaguely working code in a branch?

**Comment by simonhyde** [comment]
Now, if I'd actually saved anything, I might be able to help you! I might still have the SD card somewhere, but I don't actually have a spare Pi4 to play with at the moment. I don't think I tweaked any code, so much as just changing some makefiles to compile/link against one of the libraries linked on that page, instead of the raspberrypi openvg library.

I got far enough to get it to draw something (I don't think the sizes were necessarily right), and concluded "well, that might be fixable when I need to look at in the future", and quickly moved on to other more urgent things on my Todo list...

**Comment by peternewman** [comment]
Another option might be Vulcan:
https://www.raspberrypi.org/blog/vulkan-update-now-with-added-source-code/

**Comment by simonhyde** [comment]
Crikey. It's not like the thing would really be hitting any of the bottlnecks of OpenGL...I'd be a little reticent about adopting a standard that hasn't necessarily been widely adopted already, because that's what caused the current problems after I followed the initial advice on this great 2D Vector library that the Pi 1 supported...

That said, any move away from OpenVG would probably make it quite easy to tart up the graphics a bit with gradients and the like...

**Comment by peternewman** [comment]
Glad you've got it sorted!

Sadly Covid means my use for it has gone away for some time, although presumably helped you to find time to sort it?

Rather OT, but given I first mentioned it here, would you be interested in merging my X implementation too if I tidied it up, or would you rather keep this Pi only?

**Comment by peternewman** [comment]
Also the current code doesn't compile due to a lack of KeyCallback:
https://github.com/simonhyde/PiClock/blob/master/piclock.cpp#L1311

**Comment by simonhyde** [comment]
Right, yeah, I meant to fix that up (NULL would have sufficed, but since Ctrl+C doesn't easily quit the X version, I've added a handler to take the letter 'q' to quit)

As you noted, the "Pi4" code, is actually generic GLUT on top of OpenGL code, which is running on X. I haven't tested it on anything other than a Pi, but I don't see any reason it wouldn't work on a standard Linux install. It's just a tweak of the demo code shipped with ShivaVG, which did necessitate restructuring OpenVG to be more callback-based.

I think it would probably work on Windows too, with minor tweaks, but I don't know enough about OpenGL/GLUT on Windows to be sure.

**Comment by Capall32** [comment]
Hi, 
Nice little clock. I just built it on my pi 3B with 7 inch screen that we have in the Kitchen. Old solution I had died due to corrupt SD card and power cut.  Very nice.  thanks for sharing.
